FROM python:3.11-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        gcc \
            python3-dev \
                libpq-dev \
                    && apt-get clean \
                        && rm -rf /var/lib/apt/lists/*

                        # Copy requirements first to leverage Docker caching
                        COPY requirements/ /app/requirements/

                        # Install Python dependencies
                        RUN pip install --no-cache-dir -r requirements/prod.txt -c requirements/constraints.txt

                        # Copy application code
                        COPY . /app/

                        # Expose web server port
                        EXPOSE 8000

                        # Set environment variables
                        ENV PYTHONPATH=/app
                        ENV PYTHONUNBUFFERED=1
                        ENV DJANGO_SETTINGS_MODULE=src.settings.production

                        # Run gunicorn
                        CMD ["gunicorn", "src.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "4"]